apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: monitoring
  labels:
    name: grafana
spec:
  type: ClusterIP
  ports:
    - port: 443
      name: grafana-https
      protocol: TCP
      targetPort: 3000
  selector:
    app: grafana
