---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: blackbox-exporter
  namespace: monitoring
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: blackbox-exporter
    spec:
      containers:
        - name: blackbox-exporter
          command:
            - "/bin/blackbox_exporter"
            - "-config.file=/config/blackbox-exporter.yaml"
          image: prom/blackbox-exporter:v0.4.0
          ports:
            - containerPort: 9115
          volumeMounts:
          - name: blackbox-exporter-configmap
            mountPath: /config
      volumes:
      - name: blackbox-exporter-configmap
        configMap:
          name: blackbox-exporter-configmap
