kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: influxdb
  namespace: monitoring
  annotations:
    volume.beta.kubernetes.io/storage-class: "influxdb"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
