apiVersion: v1
kind: Service
metadata:
  name: influxdb
  namespace: monitoring
  labels:
    name: influxdb
spec:
  type: ClusterIP
  ports:
    - port: 8086
      name: influxdb-http
      protocol: TCP
      targetPort: 8086
    - port: 8089
      name: influxdb-udp
      protocol: UDP
      targetPort: 8089
    - port: 80
      name: influxdb-admin
      protocol: TCP
      targetPort: 8083
  selector:
    app: influxdb
